// AUTO-GENERATED by scripts/generate-fs-token-adapter.mjs.
// Source: sources/fs.tokens.json
// Do not edit directly. Run: npm run tokens:generate

// Default-mode primitive values remain literal to preserve saved campaign data.
export const FS_BANNER_COLORS = [
  { name: "Indigo", value: "rgba(59,71,204,1)" },
  { name: "Vermilion", value: "rgba(204,103,59,1)" },
  { name: "Amber", value: "rgba(204,173,59,1)" },
  { name: "Green", value: "rgba(59,204,98,1)" },
  { name: "Violet", value: "rgba(122,59,204,1)" },
] as const;
